// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate(arg1:string):Promise<main.UpdateInfo>;

export function CreateEvent(arg1:main.CalendarEvent):Promise<main.CalendarEvent>;

export function DeleteEvent(arg1:string):Promise<void>;

export function DownloadAndInstall(arg1:string):Promise<void>;

export function GetGoogleClientConfig():Promise<string>;

export function GetSettings():Promise<main.AppSettings>;

export function GoogleAuthURL(arg1:string):Promise<string>;

export function GoogleExchangeCode(arg1:string):Promise<main.OAuthTokens>;

export function GoogleListHolidays(arg1:string):Promise<Array<main.CalendarEvent>>;

export function GoogleLogout():Promise<void>;

export function GooglePush():Promise<main.GoogleSyncResult>;

export function GoogleRefreshTokens():Promise<main.OAuthTokens>;

export function GoogleSync():Promise<main.GoogleSyncResult>;

export function GoogleTokenInfo():Promise<main.GoogleTokenInfo>;

export function ListEvents():Promise<Array<main.CalendarEvent>>;

export function SaveGoogleClientConfig(arg1:string,arg2:string):Promise<void>;

export function SearchEvents(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<main.CalendarEvent>>;

export function UpdateEvent(arg1:main.CalendarEvent):Promise<main.CalendarEvent>;

export function UpdateSettings(arg1:main.AppSettings):Promise<main.AppSettings>;
