// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function CreateEvent(arg1) {
  return window['go']['main']['App']['CreateEvent'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DownloadAndInstall(arg1) {
  return window['go']['main']['App']['DownloadAndInstall'](arg1);
}

export function GetGoogleClientConfig() {
  return window['go']['main']['App']['GetGoogleClientConfig']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GoogleAuthURL(arg1) {
  return window['go']['main']['App']['GoogleAuthURL'](arg1);
}

export function GoogleExchangeCode(arg1) {
  return window['go']['main']['App']['GoogleExchangeCode'](arg1);
}

export function GoogleListHolidays(arg1) {
  return window['go']['main']['App']['GoogleListHolidays'](arg1);
}

export function GoogleLogout() {
  return window['go']['main']['App']['GoogleLogout']();
}

export function GooglePush() {
  return window['go']['main']['App']['GooglePush']();
}

export function GoogleRefreshTokens() {
  return window['go']['main']['App']['GoogleRefreshTokens']();
}

export function GoogleSync() {
  return window['go']['main']['App']['GoogleSync']();
}

export function GoogleTokenInfo() {
  return window['go']['main']['App']['GoogleTokenInfo']();
}

export function ListEvents() {
  return window['go']['main']['App']['ListEvents']();
}

export function SaveGoogleClientConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveGoogleClientConfig'](arg1, arg2);
}

export function SaveWindowGeometry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWindowGeometry'](arg1, arg2, arg3, arg4);
}

export function SearchEvents(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchEvents'](arg1, arg2, arg3, arg4);
}

export function SetOpacity(arg1) {
  return window['go']['main']['App']['SetOpacity'](arg1);
}

export function SetWindowPinMode(arg1) {
  return window['go']['main']['App']['SetWindowPinMode'](arg1);
}

export function StartDrag() {
  return window['go']['main']['App']['StartDrag']();
}

export function StartResize(arg1) {
  return window['go']['main']['App']['StartResize'](arg1);
}

export function UpdateEvent(arg1) {
  return window['go']['main']['App']['UpdateEvent'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
